package app
import (
 "context"; "encoding/json"; "errors"; "net/http"; "net/mail"; "strconv"; "strings"; "time"
 "livepoll/internal/auth"; "livepoll/internal/config"; "livepoll/internal/models"; "livepoll/internal/realtime"
 "github.com/gin-gonic/gin"; "github.com/golang-jwt/jwt/v5"; "github.com/google/uuid"; "github.com/gorilla/websocket"; "github.com/redis/go-redis/v9"; "go.mongodb.org/mongo-driver/bson"; "go.mongodb.org/mongo-driver/bson/primitive"; "go.mongodb.org/mongo-driver/mongo"; "go.mongodb.org/mongo-driver/mongo/options"; "golang.org/x/crypto/bcrypt"
)
type App struct{ cfg config.Config; db *mongo.Database; rdb *redis.Client; hub *realtime.Hub; up websocket.Upgrader }
func New(cfg config.Config,db *mongo.Database,rdb *redis.Client)*App{ return &App{cfg:cfg,db:db,rdb:rdb,hub:realtime.New(),up:websocket.Upgrader{CheckOrigin:func(r *http.Request)bool{return r.Header.Get("Origin")==cfg.FrontendURL}}} }
func(a *App) Indexes(ctx context.Context)error{_,e:=a.db.Collection("users").Indexes().CreateOne(ctx,mongo.IndexModel{Keys:bson.D{{Key:"email",Value:1}},Options:options.Index().SetUnique(true)});if e!=nil{return e};_,e=a.db.Collection("votes").Indexes().CreateOne(ctx,mongo.IndexModel{Keys:bson.D{{Key:"pollId",Value:1},{Key:"voterId",Value:1}},Options:options.Index().SetUnique(true)});return e}
func(a *App) Routes(r *gin.Engine){api:=r.Group("/api");api.GET("/health",func(c *gin.Context){c.JSON(200,gin.H{"status":"ok"})});api.POST("/auth/signup",a.signup);api.POST("/auth/login",a.login);api.GET("/polls/:id",a.getPoll);api.GET("/polls/:id/results",a.results);api.POST("/polls/:id/votes",a.vote);p:=api.Group("");p.Use(auth.Middleware(a.cfg.JWTSecret));p.POST("/polls",a.createPoll);p.GET("/polls/mine",a.mine);p.GET("/analytics",a.analytics);p.POST("/polls/:id/close",a.closePoll);r.GET("/ws/polls/:id",a.ws)}
func errj(c *gin.Context,s int,code,msg string){c.JSON(s,gin.H{"error":gin.H{"code":code,"message":msg}})}
func(a *App) signup(c *gin.Context){var in struct{Name,Email,Password string};if c.ShouldBindJSON(&in)!=nil{errj(c,400,"INVALID_JSON","Invalid request.");return};in.Name=strings.TrimSpace(in.Name);in.Email=strings.ToLower(strings.TrimSpace(in.Email));if len(in.Name)<2||len(in.Name)>80{errj(c,422,"INVALID_NAME","Name must be 2 to 80 characters.");return};if _,e:=mail.ParseAddress(in.Email);e!=nil{errj(c,422,"INVALID_EMAIL","Enter a valid email.");return};if len(in.Password)<8{errj(c,422,"WEAK_PASSWORD","Password must be at least 8 characters.");return};h,_:=bcrypt.GenerateFromPassword([]byte(in.Password),12);u:=models.User{Name:in.Name,Email:in.Email,PasswordHash:string(h),CreatedAt:time.Now()};res,e:=a.db.Collection("users").InsertOne(c,u);if mongo.IsDuplicateKeyError(e){errj(c,409,"EMAIL_EXISTS","Email already registered.");return};if e!=nil{errj(c,500,"SERVER_ERROR","Could not create user.");return};u.ID=res.InsertedID.(primitive.ObjectID);t,_:=auth.Token(u.ID,a.cfg.JWTSecret);c.JSON(201,gin.H{"token":t,"user":u})}
func(a *App) login(c *gin.Context){var in struct{Email,Password string};if c.ShouldBindJSON(&in)!=nil{errj(c,400,"INVALID_JSON","Invalid request.");return};var u models.User;e:=a.db.Collection("users").FindOne(c,bson.M{"email":strings.ToLower(strings.TrimSpace(in.Email))}).Decode(&u);if e!=nil||bcrypt.CompareHashAndPassword([]byte(u.PasswordHash),[]byte(in.Password))!=nil{errj(c,401,"INVALID_CREDENTIALS","Email or password is incorrect.");return};t,_:=auth.Token(u.ID,a.cfg.JWTSecret);c.JSON(200,gin.H{"token":t,"user":u})}
func(a *App) createPoll(c *gin.Context){var in struct{Question string `json:"question"`;Options []string `json:"options"`;ExpiresInHours int `json:"expiresInHours"`};if c.ShouldBindJSON(&in)!=nil{errj(c,400,"INVALID_JSON","Invalid request.");return};in.Question=strings.TrimSpace(in.Question);if len(in.Question)<5||len(in.Question)>240{errj(c,422,"INVALID_QUESTION","Question must be 5 to 240 characters.");return};if len(in.Options)<2||len(in.Options)>8{errj(c,422,"INVALID_OPTIONS","Provide 2 to 8 options.");return};if in.ExpiresInHours<0||in.ExpiresInHours>8760{errj(c,422,"INVALID_EXPIRATION","Expiration must be between 0 and 8760 hours.");return};seen:=map[string]bool{};opts:=[]models.Option{};for _,x:=range in.Options{x=strings.TrimSpace(x);k:=strings.ToLower(x);if len(x)<1||len(x)>100||seen[k]{errj(c,422,"INVALID_OPTIONS","Options must be unique and 1 to 100 characters.");return};seen[k]=true;opts=append(opts,models.Option{ID:uuid.NewString(),Text:x})};p:=models.Poll{CreatorID:c.MustGet("userID").(primitive.ObjectID),Question:in.Question,Options:opts,Status:"active",CreatedAt:time.Now()};if in.ExpiresInHours>0{expiresAt:=time.Now().Add(time.Duration(in.ExpiresInHours)*time.Hour);p.ExpiresAt=&expiresAt};res,e:=a.db.Collection("polls").InsertOne(c,p);if e!=nil{errj(c,500,"SERVER_ERROR","Could not create poll.");return};p.ID=res.InsertedID.(primitive.ObjectID);c.JSON(201,p)}
func(a *App) getPoll(c *gin.Context){id,e:=primitive.ObjectIDFromHex(c.Param("id"));if e!=nil{errj(c,400,"INVALID_ID","Invalid poll ID.");return};var p models.Poll;e=a.db.Collection("polls").FindOne(c,bson.M{"_id":id}).Decode(&p);if e!=nil{errj(c,404,"NOT_FOUND","Poll not found.");return};a.expirePoll(c,&p);_ = a.rdb.Incr(c,"poll:"+p.ID.Hex()+":views").Err();c.JSON(200,p)}
func(a *App) mine(c *gin.Context){now:=time.Now();_,_=a.db.Collection("polls").UpdateMany(c,bson.M{"creatorId":c.MustGet("userID"),"status":"active","expiresAt":bson.M{"$lte":now}},bson.M{"$set":bson.M{"status":"closed"}});cur,e:=a.db.Collection("polls").Find(c,bson.M{"creatorId":c.MustGet("userID")},options.Find().SetSort(bson.D{{Key:"createdAt",Value:-1}}));if e!=nil{errj(c,500,"SERVER_ERROR","Could not load polls.");return};ps:=make([]models.Poll,0);if cur.All(c,&ps)!=nil{errj(c,500,"SERVER_ERROR","Could not load polls.");return};c.JSON(200,ps)}
func(a *App) analytics(c *gin.Context){cur,e:=a.db.Collection("polls").Find(c,bson.M{"creatorId":c.MustGet("userID")},options.Find().SetSort(bson.D{{Key:"createdAt",Value:-1}}));if e!=nil{errj(c,500,"SERVER_ERROR","Could not load analytics.");return};polls:=make([]models.Poll,0);if cur.All(c,&polls)!=nil{errj(c,500,"SERVER_ERROR","Could not load analytics.");return};items:=make([]gin.H,0,len(polls));var totalVotes,totalViews int64;active:=0;for i:=range polls{p:=&polls[i];a.expirePoll(c,p);votes,e:=a.db.Collection("votes").CountDocuments(c,bson.M{"pollId":p.ID});if e!=nil{errj(c,500,"SERVER_ERROR","Could not load analytics.");return};views,_:=a.rdb.Get(c,"poll:"+p.ID.Hex()+":views").Int64();totalVotes+=votes;totalViews+=views;if p.Status=="active"{active++};items=append(items,gin.H{"id":p.ID.Hex(),"question":p.Question,"status":p.Status,"createdAt":p.CreatedAt,"expiresAt":p.ExpiresAt,"totalVotes":votes,"views":views,"viewers":a.hub.Count(p.ID.Hex())})};c.JSON(200,gin.H{"polls":items,"totalPolls":len(polls),"activePolls":active,"totalVotes":totalVotes,"totalViews":totalViews})}
func(a *App) closePoll(c *gin.Context){id,e:=primitive.ObjectIDFromHex(c.Param("id"));if e!=nil{errj(c,400,"INVALID_ID","Invalid poll ID.");return};res,e:=a.db.Collection("polls").UpdateOne(c,bson.M{"_id":id,"creatorId":c.MustGet("userID")},bson.M{"$set":bson.M{"status":"closed"}});if e!=nil||res.MatchedCount==0{errj(c,404,"NOT_FOUND","Poll not found or not owned by you.");return};a.publishPollUpdate(c,id,"closed");c.JSON(200,gin.H{"status":"closed"})}
func(a *App) vote(c *gin.Context){pid,e:=primitive.ObjectIDFromHex(c.Param("id"));if e!=nil{errj(c,400,"INVALID_ID","Invalid poll ID.");return};var in struct{OptionID,VoterID string};if c.ShouldBindJSON(&in)!=nil{errj(c,400,"INVALID_JSON","Invalid request.");return};if len(in.VoterID)<8||len(in.VoterID)>100{errj(c,422,"INVALID_VOTER","Invalid voter identifier.");return};var p models.Poll;if a.db.Collection("polls").FindOne(c,bson.M{"_id":pid}).Decode(&p)!=nil{errj(c,404,"NOT_FOUND","Poll not found.");return};a.expirePoll(c,&p);if p.Status!="active"{errj(c,409,"POLL_CLOSED","This poll is closed.");return};valid:=false;for _,o:=range p.Options{if o.ID==in.OptionID{valid=true}};if !valid{errj(c,422,"INVALID_OPTION","Option does not belong to this poll.");return};v:=models.Vote{PollID:pid,OptionID:in.OptionID,VoterID:in.VoterID,CreatedAt:time.Now()};_,e=a.db.Collection("votes").InsertOne(c,v);if mongo.IsDuplicateKeyError(e){errj(c,409,"ALREADY_VOTED","You have already voted.");return};if e!=nil{errj(c,500,"SERVER_ERROR","Could not record vote.");return};key:="poll:"+pid.Hex()+":counts";_,e=a.rdb.HIncrBy(c,key,in.OptionID,1).Result();if e!=nil{_,_=a.rebuild(c,p)};snap,_:=a.snapshot(c,p);b,_:=json.Marshal(snap);_ = a.rdb.Publish(c,"poll:"+pid.Hex()+":updates",b).Err();c.JSON(201,snap)}
func(a *App) results(c *gin.Context){id,e:=primitive.ObjectIDFromHex(c.Param("id"));if e!=nil{errj(c,400,"INVALID_ID","Invalid poll ID.");return};var p models.Poll;if a.db.Collection("polls").FindOne(c,bson.M{"_id":id}).Decode(&p)!=nil{errj(c,404,"NOT_FOUND","Poll not found.");return};a.expirePoll(c,&p);snap,e:=a.snapshot(c,p);if e!=nil{snap,e=a.rebuild(c,p)};if e!=nil{errj(c,500,"SERVER_ERROR","Could not load results.");return};c.JSON(200,snap)}
func(a *App) expirePoll(c *gin.Context,p *models.Poll){if p.Status=="active"&&p.ExpiresAt!=nil&&!p.ExpiresAt.After(time.Now()){p.Status="closed";res,e:=a.db.Collection("polls").UpdateOne(c,bson.M{"_id":p.ID,"status":"active"},bson.M{"$set":bson.M{"status":"closed"}});if e==nil&&res.ModifiedCount>0{a.publishPollUpdate(c,p.ID,"closed")}}}
func(a *App) publishPollUpdate(ctx context.Context,id primitive.ObjectID,status string){payload,_:=json.Marshal(gin.H{"type":"poll.updated","pollId":id.Hex(),"status":status});_ = a.rdb.Publish(ctx,"poll:"+id.Hex()+":updates",payload).Err()}
func(a *App) snapshot(ctx context.Context,p models.Poll)(models.Snapshot,error){m,e:=a.rdb.HGetAll(ctx,"poll:"+p.ID.Hex()+":counts").Result();if e!=nil{return models.Snapshot{},e};if len(m)==0{return a.rebuild(ctx,p)};rs:=[]models.Result{};var total int64;for _,o:=range p.Options{n,_:=strconv.ParseInt(m[o.ID],10,64);rs=append(rs,models.Result{OptionID:o.ID,Count:n});total+=n};return models.Snapshot{Type:"results.updated",PollID:p.ID.Hex(),Results:rs,TotalVotes:total},nil}
func(a *App) rebuild(ctx context.Context,p models.Poll)(models.Snapshot,error){pipe:=a.rdb.TxPipeline();key:="poll:"+p.ID.Hex()+":counts";pipe.Del(ctx,key);rs:=[]models.Result{};var total int64;for _,o:=range p.Options{n,e:=a.db.Collection("votes").CountDocuments(ctx,bson.M{"pollId":p.ID,"optionId":o.ID});if e!=nil{return models.Snapshot{},e};pipe.HSet(ctx,key,o.ID,n);rs=append(rs,models.Result{OptionID:o.ID,Count:n});total+=n};_,e:=pipe.Exec(ctx);return models.Snapshot{Type:"results.updated",PollID:p.ID.Hex(),Results:rs,TotalVotes:total},e}
func(a *App) ws(c *gin.Context){room:=c.Param("id");id,e:=primitive.ObjectIDFromHex(room);if e!=nil{c.Status(400);return};var poll models.Poll;if a.db.Collection("polls").FindOne(c,bson.M{"_id":id}).Decode(&poll)!=nil{c.Status(404);return};conn,e:=a.up.Upgrade(c.Writer,c.Request,nil);if e!=nil{return};count:=a.hub.Add(room,conn);broadcastViewers:=func(count int){payload,_:=json.Marshal(gin.H{"type":"viewers.updated","pollId":room,"viewers":count});a.hub.Broadcast(room,payload)};broadcastViewers(count);defer func(){broadcastViewers(a.hub.Remove(room,conn))}();ctx,cancel:=context.WithCancel(c.Request.Context());defer cancel();sub:=a.rdb.Subscribe(ctx,"poll:"+room+":updates");defer sub.Close();if _,e=sub.Receive(ctx);e!=nil{return};messages:=sub.Channel();readErrors:=make(chan error,1);go func(){for{if _,_,readErr:=conn.ReadMessage();readErr!=nil{readErrors<-readErr;return}}}();for{select{case message,ok:=<-messages:if !ok{return};a.hub.Send(conn,[]byte(message.Payload));case <-readErrors:return;case <-ctx.Done():return}}}
var _ = errors.New; var _ = jwt.ErrTokenExpired
